### ISSUE TITLE
Question: why do I have too small screen resolution inside the docker container?

### ISSUE THREAD

**Issue by w32blaster** [khozzy/docker#1]
Hi there,

first of all, thanks for this amazing containers, I use them to run my Selenium/Selenide tests in my projects! But I have small issue there. The screen resolution is pretty small. I see you set it here to 1024x768:

https://github.com/khozzy/docker/blob/master/selenium_java_firefox/libs/xvfb_init#L2

But when I do screenshots of the Firefox browser during my tests I can see that the screen width is about 760px. Do you have any suggestion where I can start debugging? How I can force to use proper screen resolution? I run tests inside our GitLabCI server, so may be the CI itself prevents somehow to use higher resolution?

I would be happy to get any suggestion :)
Thank you!

**Comment by khozzy** [comment]
Hi, unfortunately I had not tried to take screenshot inside this container. I would start by looking into XVFB arguments and parameters, maybe there would be something interesting.

— Norbert Kozłowski
On Mon, Jul 3, 2017 at 14:51, Ilja Hämäläinen <notifications@github.com> wrote:
Hi there,

first of all, thanks for this amazing containers, I use them to run my Selenium/Selenide tests in my projects! But I have small issue there. The screen resolution is pretty small. I see you set it here to 1024x768:

https://github.com/khozzy/docker/blob/master/selenium_java_firefox/libs/xvfb_init#L2 [https://github.com/khozzy/docker/blob/master/selenium_java_firefox/libs/xvfb_init#L2]

But when I do screenshots of the Firefox browser during my tests I can see that the screen width is about 760px. Do you have any suggestion where I can start debugging? How I can force to use proper screen resolution? I run tests inside our GitLabCI server, so may be the CI itself prevents somehow to use higher resolution?

I would be happy to get any suggestion :)
Thank you!

**Comment by w32blaster** [comment]
sure. Ok, thanks anyway! Cheers!
